- assets/fireworkx-product-image-slider.css
- assets/fireworkx-product-image-slider.js
- sections/fireworkx-about-us-slider.liquid
- sections/main-product.liquid
- templates/index.json
Created the product detail image customized slider
* Replace the shopify default slider with the Slider JS library slider
* Styled the slider image to be responsive
* Store : http://127.0.0.1:9292/products/ranger-single-cab-canopy-roadrunner-2012-to-current
* Editor : https://andycab.myshopify.com/admin/themes/127080202411/editor?previewPath=%2Fproducts%2Franger-single-cab-canopy-roadrunner-2012-to-current
Followed theme code principles
Linted with Theme Check
Tested on mobile
Tested on multiple browsers
Tested for accessibility
> Fwx product detail page slider

- sections/fireworkx-image-banner.liquid
- sections/fireworkx-why-choose-andycab.liquid
Added presets in the schema for the Image banner and Why AndyCab sections
> Fwx image banner fix

- layout/theme.liquid
* Changes 
- Added google tag manager in the theme file
> features : adding google tag manager

- assets/fireworkx-error-message.css
- assets/fireworkx-main-product.css
- assets/fireworkx-quote-slider.js
- assets/fireworkx-success-message.css
- assets/section-product-recommendations.css
- sections/fireworkx-quote-slider.liquid
- snippets/fireworkx-error-message.liquid
- snippets/fireworkx-product-form.liquid
- snippets/fireworkx-success-message.liquid
1. Margin on the product page 
2. Message notification after form submitted
> feautres : notification message after form submit

- assets/fireworkx-footer.css
- sections/fireworkx-footer.liquid
- snippets/fireworkx-get-in-touch.liquid
- snippets/fireworkx-need-help-or-quote.liquid
- snippets/fireworkx-need-to-chat.liquid
Added the JHB number in Andycab as required
> feature : added jhb number in andycab

- locales/en.default.json
- snippets/fireworkx-need-to-chat.liquid
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> update : text change on product card

- assets/fireworkx-base.css
- assets/section-main-product.css
- sections/fireworkx-quote-slider.liquid
- snippets/andycab-gallery-modal.liquid
- snippets/andycab-whatsapp-widget.liquid
- snippets/fireworkx-product-form.liquid
- snippets/price.liquid
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Sale price update

- snippets/fireworkx-product-form.liquid
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> commit to new branch

- sections/fireworkx-footer.liquid
- snippets/fireworkx-get-in-touch.liquid
* Updated the contact details information - added the provinces on the footer and contact us page
> update : added provinces in the contact number

- assets/fireworkx-base.css
- snippets/fireworkx-need-help-or-quote.liquid
Added contact update for the Need a quote snippet
> update : added contact numbers

- assets/base.css
- sections/fireworkx-quote-slider.liquid
- snippets/fireworkx-product-form.liquid
style : make texarea non required and add visibility on button on safari
> style : make texarea non required and add visibility on button on safari

- snippets/icon-close.liquid
Fix : Fixed the button visibilty on safari
> fix : make the close button visible on safari

- assets/component-card.css
- assets/fireworkx-component-card.css
fix the styling of the badge icon (discount ) on mobile and tablet for collection of products
> style-fix : fix discount badge icon on mobile

- assets/base.css
- assets/component-card.css
- assets/fireworkx-base.css
- assets/fireworkx-component-card.css
- assets/fireworkx-header.css
- assets/fireworkx-how-buying-online.css
- assets/fireworkx-main-product.css
- config/settings_data.json
- sections/contact-form.liquid
- sections/fireworkx-footer.liquid
- sections/fireworkx-how-buying-online.liquid
- sections/fireworkx-image-banner.liquid
- sections/fireworkx-main-product.liquid
- sections/fireworkx-quote-slider.liquid
- snippets/andycab-gallery-modal.liquid
- snippets/fireworkx-get-in-touch.liquid
- snippets/fireworkx-need-help-or-quote.liquid
- snippets/fireworkx-need-to-chat.liquid
- snippets/fireworkx-product-form.liquid
- snippets/icon-close.liquid
- templates/index.json
- templates/page.fitment-centres.json
- templates/page.spares-repairs.json
- templates/product.json
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Fwx how buying online

- sections/fireworkx-main-product-dawn-9.liquid
Committed from shop: AndyCab
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Update from Shopify for theme Shopify-AndyCab/Development-latest

- assets/fireworkx-main-product-dawn-9.css
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Development latest

- assets/fireworkx-error-message.css
- assets/fireworkx-success-message.css
- layout/theme.liquid
- snippets/fireworkx-success-message.liquid
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Add styling to enquiry success message + add unique ID to Success message

- assets/fireworkx-quote-slider.js
- snippets/fireworkx-success-message.liquid
- templates/page.fitment-centres.json
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Remove datalayer push on form submit

- assets/fireworkx-base.css
- assets/fireworkx-fitment-centre.css
- assets/fireworkx-image-with-text.css
- layout/theme.liquid
- sections/fireworkx-fitment-centre-group.liquid
- sections/multicolumn.liquid
- templates/collection.accessories.json
- templates/collection.ford-canopies.json
- templates/collection.gwm-canopies.json
- templates/collection.hyundai-canopies.json
- templates/collection.isuzu-canopies.json
- templates/collection.jac-canopies.json
- templates/collection.json
- templates/collection.kia-canopies.json
- templates/collection.mahindra-canopies.json
- templates/collection.mazda-canopies.json
- templates/collection.new-canopies.json
- templates/collection.nissan-canopies.json
- templates/collection.suzuki-canopies.json
- templates/collection.toyota-canopies.json
- templates/collection.used-canopies.json
- templates/collection.volkswagen-canopies.json
- templates/page.contact.json
- templates/page.fitment-centres.json
- templates/page.spares-repairs.json
- templates/product.json
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Custom liquid spacing issues, fitment centre padding + fireworks image with text padding

- assets/fireworkx-base.css
- assets/fireworkx-header.css
- templates/collection.ford-canopies.json
- templates/collection.gwm-canopies.json
- templates/collection.hyundai-canopies.json
- templates/collection.isuzu-canopies.json
- templates/collection.jac-canopies.json
- templates/collection.kia-canopies.json
- templates/collection.mahindra-canopies.json
- templates/collection.mazda-canopies.json
- templates/collection.new-canopies.json
- templates/collection.nissan-canopies.json
- templates/collection.suzuki-canopies.json
- templates/collection.used-canopies.json
- templates/collection.volkswagen-canopies.json
Committed from shop: AndyCab
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Fix spacing issue with nav dropdown

- templates/collection.ford-canopies.json
- templates/collection.gwm-canopies.json
- templates/collection.hyundai-canopies.json
- templates/collection.isuzu-canopies.json
- templates/collection.jac-canopies.json
- templates/collection.kia-canopies.json
- templates/collection.mahindra-canopies.json
- templates/collection.mazda-canopies.json
- templates/collection.new-canopies.json
- templates/collection.nissan-canopies.json
- templates/collection.suzuki-canopies.json
- templates/collection.used-canopies.json
- templates/collection.volkswagen-canopies.json
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> Bring latest content into development

- assets/fireworkx-why-choose-andycab.css
- layout/theme.liquid
- sections/collage.liquid
- sections/fireworkx-footer.liquid
- sections/fireworkx-why-choose-andycab-home.liquid
- sections/fireworkx-why-choose-andycab.liquid
- sections/video.liquid
- snippets/fireworkx-get-in-touch.liquid
- snippets/fireworkx-need-help-or-quote.liquid
- snippets/fireworkx-need-to-chat.liquid
- templates/index.json
Fixes #0.
**Demo links**
- [Store](url)
**Checklist**
> New why Andy Cab section on home page

- assets/fireworkx-main-product.css
- sections/fireworkx-main-product-dawn-9.liquid
Add the metadata in the product card
> feature : add DMS data on product card
